# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdf60673979dbaec4247fdd99ea20ba91650fdf60626acff9f1787d6e280747806aa9ca643af9e633d0daeea893e0e7b45e98765ee7673fc29b4022a9512a925

test:
  secret_key_base: e88e2d5471ef8e10b02f74557cd24f9c6a4a56dce594b74388b66f719ee57677f5832300a1023e7ad97a500bae9fc145d70f8ca45b7ca6f7233c0139fc729be5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
